
def add_base_path(file_path: str, root_full_path: str) -> str:
    """
    This function adds a full path to the config file.

    Parameters
    ----------
    file_path: str
        This parameter specifies the file location path.
    root_full_path: str
        This parameter retrieves the full path for the file.

    Returns
    -------
    file_path: str
        The return value is a complete path generated by combining the file_path and root_full_path parameters.
    """

    if file_path.startswith("./"):
        file_path = file_path.replace('./', root_full_path + '/')
    else:
        file_path = f"{root_full_path}/{file_path}"

    return file_path
